export const PLUGIN_ID = 'plot-summary'

export const DIALOG_SESSION = 'session'
export const DIALOG_MANUAL = 'manual'
export const DIALOG_ENABLE = 'enable'
export const DIALOG_REVIEW = 'review'
export const DIALOG_REVIEW_SIDECAR = 'review-sidecar'
export const DIALOG_PICK_LOREBOOK = 'pick-lorebook'
export const DIALOG_RECOVER_LOREBOOK = 'recover-lorebook'
export const DIALOG_PROMPT_PREVIEW = 'prompt-preview'
